### ISSUE TITLE
Advanced connection management

### ISSUE THREAD

**Issue by axilirator** [axilirator/tmsi-sniffer#2]
We should be able to:
- see connections list;
- close specific connection;
- send a command to a specific slave.

To do this, we need to assign an unique ID to every new connection.

**Comment by BlackPhreaker** [comment]
Добрый день Вадим... Возник такой вопрос при запуски вашего IMSI Catchera () возникает ошибка... Не подскажите почему???

***
root@kali:~/Desktop/tmsi-sniffer-master# ./sdr_tmsi_map.py
Copyright (C) 2016 by Vadim Yanitskiy <axilirator@gmail.com>
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

[i] Init Control interface
[i] Connecting to 127.0.0.1:8888...
[i] Init Radio interface
gr-osmosdr v0.1.4-72-g164a09fc (0.1.5git) gnuradio 3.7.9
built-in source types: file osmosdr fcd rtl rtl_tcp rfspace redpitaya 
Using device #0 Realtek RTL2838UHIDIR SN: 00000001
Found Rafael Micro R820T tuner
[R82XX] PLL not locked!
Exact sample rate is: 2000000.052982 Hz
Traceback (most recent call last):
  File "./sdr_tmsi_map.py", line 385, in <module>
    Application().run()
  File "./sdr_tmsi_map.py", line 264, in run
    self.phy_ppm, self.local_port)
  File "/root/Desktop/tmsi-sniffer-master/lib/radio.py", line 95, in __init__
    shift_fc, self.samp_rate, osr = 4)
TypeError: make() takes exactly 1 argument (3 given)
***

**Comment by axilirator** [comment]
Здравствуйте! Во-первых, это не IMSI Catcher, будьте добры прочитать описание.
Касательно вашей проблемы, я только что проверил на свежих версиях GNURadio и
GR-GSM - все работает без проблем. Попробуйте обновиться.
